Hotfix/device actions
nguyer/homeassistant-bond-home pull request #5
Opened 2019-11-30 21:05 UTC by bcb2000

Added support for fan speed control.  Limitations - I have only supported the home assistant out of the box 3 speeds, low, medium and high.  These will be mapped to Bond Fan speeds as low = 1, high = whatever the highest is and medium = a sensible number in between.  This code is only tested on fans with 3 speeds.

2019-12-01 00:10 UTC, nguyer commented
This looks pretty good (aside from my comments in https://github.com/nguyer/homeassistant-bond-home/pull/4). My fans have like 8 speeds I think, so I can test it out on them too. Thanks for adding this!

2019-12-13 13:49 UTC, Timp103 commented
I’ve tested this and now I do have access to the fan speed drop down select. However there is still 2 issues. For some reasons my choices are (low, medium, medium, high) I believe one of the options should also be ‘off’ and as you can see there are two ‘medium’ options. Also no matter which speed I select my fan only Uses whichever speed I selected last time using the bond app on my phone. It makes no changes to the speed at all.

2019-12-13 13:50 UTC, niemyjski commented
Does this add support for fireplaces too?

2019-12-13 15:10 UTC, Timp103 commented on custom_components/bond/bond.py
> +        return self.doAction(deviceId, BOND_DEVICE_ACTION_SETSPEED, {"argument":speed} )
return self.doAction(deviceId, BOND_DEVICE_ACTION_SETSPEED, {"argument": speed} )

2019-12-13 15:15 UTC, ViolentPoo requested changes
LINE 48 of bond.py needs a space in the argument

2019-12-13 15:15 UTC, Timp103 commented on custom_components/bond/fan.py
> +                self._speed_list.append(SPEED_HIGH)
if BOND_DEVICE_ACTION_SETSPEED in self._device['actions']:
                self._speed_low = int(1)
                self._speed_list.append(SPEED_LOW)
                self._speed_medium = int(2)
                self._speed_list.append(SPEED_MEDIUM)
                self._speed_high = int(3)
                self._speed_list.append(SPEED_HIGH)

2019-12-13 15:15 UTC, Timp103 commented on custom_components/bond/bond.py
> +        return self.doAction(deviceId, BOND_DEVICE_ACTION_SETSPEED, {"argument":speed} )
return self.doAction(deviceId, BOND_DEVICE_ACTION_SETSPEED, {"argument":  speed} )

2019-12-13 15:16 UTC, Timp103 commented
With the above changes it works flawlessly on 3 of my ceiling fans

2020-01-17 01:18 UTC, nguyer commented
Closed, due to https://github.com/nguyer/homeassistant-bond-home/pull/11 superseding this PR

2020-01-17 01:18 UTC, closed without merging